apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# XXX :: GjB :: ⚠️ NO NOT SET NAMESPACE ⚠️ -- it will override roles for kube-system needed for leader election of cainjector
# namespace: cert-manager
resources:
  - ./namespace.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io/
    version: v1.10.2
    namespace: cert-manager
    releaseName: cert-manager
    includeCRDs: true
    valuesInline:
      installCRDs: true
