apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atomic-nucleus/atomic-nucleus.com/
    path: gitops/apps/cert-manager
  destination:
    name: in-cluster
    namespace: cert-manager
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
